apiVersion: v1
kind: Service
metadata:
  name: jib-k8s-limits-shenandoah-example-http
  labels:
    app: jib-k8s-limits-shenandoah-example-http
spec:
  selector:
    app: jib-k8s-limits-shenandoah-example
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: jib-k8s-limits-shenandoah-example-actuator
  labels:
    app: jib-k8s-limits-shenandoah-example-actuator
spec:
  selector:
    app: jib-k8s-limits-shenandoah-example
  ports:
  - name: actuator
    port: 8081
    targetPort: 8081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jib-k8s-limits-shenandoah-example
  labels:
    app: jib-k8s-limits-shenandoah-example
spec:
  selector:
    matchLabels:
      app: jib-k8s-limits-shenandoah-example
  replicas: 1
  template:
    metadata:
      labels:
        app: jib-k8s-limits-shenandoah-example
    spec:
      containers:
      - name: jib-k8s-limits-shenandoah-example
        image: index.docker.io/svenbayer/jib-k8s-limits-shenandoah-example:1.0.0-SNAPSHOT
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 9000
        resources:
          limits:
            memory: 300Mi
            cpu: 1
          requests:
            memory: 200Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 3
      imagePullSecrets:
      - name: regcred